# Generated by Django 3.1.7 on 2021-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=16)),
            ],
        ),
    ]
