# Generated by Django 3.1.7 on 2021-05-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miaTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ad_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ad_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('co_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=5)),
                ('co_src', models.URLField()),
                ('co_price', models.FloatField()),
                ('co_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=5)),
                ('co_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miaTest.commodity')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miaTest.user')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=5)),
                ('sales_num', models.IntegerField()),
                ('co_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miaTest.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('order_num', models.IntegerField()),
                ('user_phone', models.CharField(max_length=11)),
                ('co_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miaTest.commodity')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miaTest.user')),
            ],
        ),
    ]
