# Generated by Django 3.1.7 on 2021-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaTest', '0002_auto_20210502_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_active',
            fields=[
                ('ad_active', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
