# Generated by Django 3.1.7 on 2021-05-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miaTest', '0003_ad_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_active',
            old_name='ad_active',
            new_name='ad_ac',
        ),
    ]
